### ISSUE TITLE
Swift Concurrency Import Issues

### ISSUE THREAD

**Issue by alex-taffe** [Giphy/giphy-ios-sdk#190] opened 2022-01-10 16:29 UTC
Some of our clients are still on Xcode 12.x and newer versions of Giphy fail to compile due to:
```
/Giphy/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule/arm64-apple-ios.swiftinterface:12:8: [31mno such module '_Concurrency'[0m

import _Concurrency
[36m                            ^[0m
```

A line such as:
```
#if compiler(>=5.5) && canImport(_Concurrency)
```
May be necessary, not sure how this works with precompiled frameworks. An `@available` may be the correct option too

**Comment by cgmaier** [comment] 2022-01-26 04:30
hey @alex-taffe sorry for the late reply - this appears to be expected behavior due to [changes](https://developer.apple.com/forums/thread/690350) in Swift 5.5.  

we understand closed source frameworks built in swift such as ours are prone to these sorts of (hopefully) rare but frustrating issues and we appreciate everyone's patience in continuing to use the GIPHY SDK. 

gonna go ahead and close this, but feel free to drop any suggestions if there's something actionable we can do on our end. 

cc @ALexanderLonsky

**Closed by cgmaier** 2022-01-26 04:30 UTC
